services:
  - type: web
    name: med-image-ai
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn -c gunicorn_config.py wsgi:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.18
